package Lab7;

import SimpArc.transd;
import simView.ViewableAtomic;
import simView.ViewableComponent;
import simView.ViewableDigraph;

import java.awt.*;

public class queue_model extends ViewableDigraph
{

	public queue_model()
	{
		super("gpt");
    	
		ViewableAtomic g = new Generator("Generator", 30);
		ViewableAtomic p = new Processor("Processor", 70);
		ViewableAtomic q = new Queue("Queue", 10);
    	
		add(g);
		add(p);
		add(q);
  
		addCoupling(g, "out", q, "in_1");
		addCoupling(q, "out", p, "in");
		addCoupling(p, "out_1", g, "in");
		addCoupling(p, "out_2", q, "in_2");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("Queue")).setPreferredLocation(new Point(639, 117));
        ((ViewableComponent)withName("Processor")).setPreferredLocation(new Point(465, 476));
        ((ViewableComponent)withName("Generator")).setPreferredLocation(new Point(59, 148));
    }
}
